# Generated by Django 4.2.2 on 2023-07-11 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("statement", models.TextField()),
                ("code", models.CharField(max_length=10)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        default="EASY",
                        max_length=6,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.TextField()),
                ("output", models.TextField()),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="judge.problem"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("COMPILATION ERROR", "Compilation Error"),
                            ("WRONG ANSWER", "Wrong Output"),
                            ("TIME LIMIT EXCEEDED", "Time Limit Exceeded"),
                            ("RUNTIME ERROR", "Runtime Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("submittedAt", models.DateTimeField(auto_now_add=True)),
                ("language", models.CharField(max_length=10)),
                ("code", models.TextField()),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="judge.problem"
                    ),
                ),
            ],
        ),
    ]
